### ISSUE TITLE
Alto compatibility with phyloseq

### ISSUE THREAD

**Issue by mirpie** [lasy/alto#25]
Hello!
I've been going through the tutorial/sample code on how to implement alto with a set of microbiome data. I noticed that the sample data format is very similar to a phyloseq object, plus minus some wrangling on the taxonomy table. Is there a reason why the example provided isn't compatible with a phyloseq object, and is there anything to watch out for if trying to convert a phyloseq object into the required format?

Thanks!

**Comment by krisrs1128** [comment]
I'm sorry for the delay! Conceptually, there shouldn't be anything that prevents creation of the alto input from a phyloseq object, and creating an illustrative example seems like a good idea.

Did you run into any difficulties forming the input data / using the package?
